name: Pull Request Security Audit

on:
  push:
    paths:
      - '**/Cargo.toml'
  pull_request:
    paths:
      - '**/Cargo.toml'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Install cargo-audit
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: install
          args: cargo-audit

      - name: Generate lockfile
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: generate-lockfile

      - name: Audit dependencies
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: audit
